name: reviewdog
on: push

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        with:
          reporter: github-check
          fail_on_error: true
          level: warning
          debug: true
